FROM --platform=linux/amd64 public.ecr.aws/lambda/python:3.12
RUN dnf install -y poppler-utils && dnf clean all
COPY requirements.txt pyproject.toml ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
RUN pip install -e .
CMD ["main.handler"]
